In [2]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [14]:
env= gym.make("FrozenLake-v1",is_slippery=False)

In [15]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size,action_space_size))
print(q_table.shape)


(16, 4)


In [16]:
print(action_space_size)
print(state_space_size)

4
16


In [17]:
env.reset()

(0, {'prob': 1})

In [18]:
env.action_space.sample()

0

In [19]:
env.step(0)

c:\Users\KIIT\AppData\Local\Programs\Python\Python311\Lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


(0, 0.0, False, False, {'prob': 1.0})

In [40]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [41]:
q_table

array([[0.94148015, 0.95099005, 0.95099005, 0.94148015],
       [0.94148015, 0.        , 0.96059601, 0.95098614],
       [0.95098737, 0.970299  , 0.95087156, 0.96058765],
       [0.96057717, 0.        , 0.8911979 , 0.93705022],
       [0.95099005, 0.96059601, 0.        , 0.94148015],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.9801    , 0.        , 0.96045992],
       [0.        , 0.        , 0.        , 0.        ],
       [0.96059601, 0.        , 0.970299  , 0.95099005],
       [0.96059601, 0.9801    , 0.9801    , 0.        ],
       [0.97029894, 0.99      , 0.        , 0.97029693],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.9801    , 0.99      , 0.970299  ],
       [0.9801    , 0.99      , 1.        , 0.9801    ],
       [0.        , 0.        , 0.        , 0.        ]])

In [42]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()[0]
    done = False 
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate<exploration_rate_threshold:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
        new_state, reward, done,info,_ = env.step(action)
        print(state,new_state,action)
        q_table[state,action] = q_table[state, action] * (1-learning_rate) + learning_rate*(reward+discount_rate*np.max(q_table[new_state, :]))
        state = new_state
        rewards_current_episode += reward

        if done == True:
            break
    exploration_rate = min_exploration_rate + (max_exploration_rate-min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    rewards_all_episodes.append(rewards_current_episode)


0 0 3
0 1 2
1 5 1
0 1 2
1 5 1
0 0 0
0 4 1
4 0 3
0 0 3
0 0 0
0 0 0
0 0 0
0 0 0
0 1 2
1 2 2
2 2 3
2 2 3
2 3 2
3 3 2
3 3 2
3 3 3
3 2 0
2 6 1
6 7 2
0 0 3
0 0 0
0 0 0
0 0 3
0 4 1
4 4 0
4 0 3
0 0 3
0 1 2
1 0 0
0 4 1
4 0 3
0 0 0
0 1 2
1 2 2
2 2 3
2 6 1
6 7 2
0 4 1
4 8 1
8 8 0
8 12 1
0 4 1
4 0 3
0 0 0
0 4 1
4 0 3
0 0 3
0 0 3
0 1 2
1 1 3
1 5 1
0 0 3
0 1 2
1 5 1
0 4 1
4 4 0
4 0 3
0 0 0
0 1 2
1 0 0
0 1 2
1 2 2
2 3 2
3 3 3
3 3 2
3 3 2
3 7 1
0 4 1
4 5 2
0 4 1
4 4 0
4 0 3
0 0 0
0 1 2
1 0 0
0 0 3
0 0 3
0 1 2
1 5 1
0 0 0
0 0 0
0 1 2
1 2 2
2 1 0
1 5 1
0 1 2
1 1 3
1 2 2
2 2 3
2 3 2
3 3 3
3 3 2
3 2 0
2 3 2
3 3 2
3 7 1
0 0 3
0 0 3
0 4 1
4 4 0
4 5 2
0 1 2
1 0 0
0 0 3
0 4 1
4 0 3
0 0 3
0 1 2
1 5 1
0 4 1
4 4 0
4 4 0
4 5 2
0 0 0
0 4 1
4 4 0
4 0 3
0 4 1
4 4 0
4 8 1
8 12 1
0 1 2
1 0 0
0 4 1
4 0 3
0 1 2
1 0 0
0 0 0
0 4 1
4 5 2
0 0 3
0 4 1
4 4 0
4 5 2
0 1 2
1 2 2
2 2 3
2 2 3
2 3 2
3 3 2
3 7 1
0 0 3
0 1 2
1 0 0
0 1 2
1 2 2
2 6 1
6 5 0
0 0 3
0 4 1
4 4 0
4 4 0
4 8 1
8 4 3
4 5 2
0 1 2
1 5 1
0 0 0
0 1 2
1 2 2
2 3 2
3 

In [43]:

rewards_per_thousand_episodes=np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("***********Average rewards per thousand episodes***********\n")
for r in rewards_per_thousand_episodes:
    print(count,": ",str(sum(r/1000)))
    count+=1000



***********Average rewards per thousand episodes***********

1000 :  0.2800000000000002
2000 :  0.7380000000000005
3000 :  0.9080000000000007
4000 :  0.9580000000000007
5000 :  0.9810000000000008
6000 :  0.9870000000000008
7000 :  0.9920000000000008
8000 :  0.9950000000000008
9000 :  0.9910000000000008
10000 :  0.9870000000000008


In [44]:
print("\n\n*******Q-table*******\n")
print(q_table)



*******Q-table*******

[[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.9509876  0.960596  ]
 [0.96059512 0.         0.93990395 0.9477962 ]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059222]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.97029898]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299  ]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.        ]]
